Separated 14.10_ng and 14.04_ng scripts
There were getting to be too many differences between the two scripts to
keep it as one script and keep adding random changes that Ubuntu 14.10
didn't need. I reverted the 14.10 script and all accompanying scripts
to a few commits ago when it was working fine, made the 14.04 script an
independant file instead of a symlink, and took out 14.04_ng's version
checks, since we now know it's definately running 14.04

diff --git a/extras_14.04/RAM_Session/rlib b/extras_14.04/RAM_Session/rlib
--- a/extras_14.04/RAM_Session/rlib
+++ b/extras_14.04/RAM_Session/rlib
@@ -220,6 +220,31 @@ MOUNT_RS()
 	}
 }
 
+#Recursive umount function
+#Ubuntu 14.04 does not have 'umount -R' option
+#This function simulates that functionality
+#Args:
+#	$1 - Dir to recursively unmount
+#Returns:
+#	0 if everything unmounted successfully
+#	1 if something failed to unmount
+RUMOUNT()
+{
+	#Figure out dirs to unmount
+	#Note: The 'sort -r' is VERY IMPORTANT - it sorts the mountpoints
+	#	in a way that's deepest first
+	DIRS_TO_UNMOUNT=$(df -a | grep ${1%/} | tr -s " " | cut -d " " -f 6- | sort -r)
+
+	for UDIR in $DIRS_TO_UNMOUNT
+	do
+		umount $UDIR 2>/dev/null
+		if [[ $? != 0 ]]
+		then
+			return 1
+		fi
+	done
+}
+
 #Unmount $DEST (RAM Session)
 UMOUNT_RS()
 {
@@ -286,7 +311,7 @@ UMOUNT_RS()
 			echo $FS | grep -qx "/home" && continue
 			echo $FS | grep -qx "/run/user" && continue
 			umount "$FS" &>/dev/null
-		done < <(df | tail -n+2 | tr -s " " | cut -d " " -f 6- | sort -r)'
+		done < <(df 2>/dev/null | tail -n+2 | tr -s " " | cut -d " " -f 6- | sort -r)'
 
 		#Find processes who's root folder is actually the chroot
 		for ROOT in $(find /proc/*/root)
@@ -301,7 +326,7 @@ UMOUNT_RS()
 	fi
 
 	#Unmount all filesystems under $Orig_OS recursively
-	sudo umount -R $Orig_OS 2>/dev/null
+	RUMOUNT $Orig_OS
 
 	#Check how it went
 	if [[ "$?" == 0 ]]
@@ -359,7 +384,7 @@ UMOUNT_RS()
 			#Try unmounting again:
 
 			#Unmount all filesystems under $Orig_OS recursively
-			sudo umount -R $Orig_OS 2>/dev/null
+			RUMOUNT $Orig_OS
 
 			if [[ "$?" == "0" ]]
 			then
