Almost done Uninstall function - just needs testing

diff --git a/extras_14.10/ram_lib b/extras_14.10/ram_lib
--- a/extras_14.10/ram_lib
+++ b/extras_14.10/ram_lib
@@ -157,6 +157,72 @@ Uninstall_RAM_Booster() {
 		sudo rm -f /etc/ram_booster.conf
 	fi
 
+	#Delete /live
+        if [[ -d /live ]]; then 
+		echo
+                echo "Removing /live..."
+                sudo rm -rf /live &>/dev/null
+
+		#Check how delete operation went
+		if [[ "$?" != "0" ]]
+		then
+			echo "Failed to remove /live"
+		fi
+        fi
+
+	#Delete /etc/grub.d/06_RAMSESS
+	if [[ -e /etc/grub.d/06_RAMSESS ]]
+	then
+		echo
+		echo "Removing /etc/grub/06_RAMSESS..."
+		sudo rm -f /etc/grub/06_RAMSESS
+	fi
+
+	#Delete log file
+	if [[ -e $LOG ]]
+	then
+		echo
+		echo "Removing $LOG..."
+		sudo rm -f "$LOG"
+	fi
+
+	#Delete /Original_OS
+	if [[ -e /Original_OS ]]
+	then
+		echo
+		echo "Removing /Original_OS..."
+		sudo rm -f /Original_OS
+	fi
+
+	#Fix grub menu
+	echo
+	echo "Restoring grub menu..."
+	sudo sed -i 's/#\(GRUB_HIDDEN_TIMEOUT=0\)/\1/g' /etc/default/grub
+
+	#Fix /etc/grub.d/10_linux
+
+	#Update grub
+	echo
+	echo "Updating grub:"
+	sudo update-grub
+
+	#Purge live-boot
+	echo
+	echo "Purging live-boot..."
+	sudo apt-get -y purge live-boot &>/dev/null
+
+	if [[ "$?" != "0" ]]
+	then
+		echo "Failed to purge live-boot"
+	fi
+
+	#Tell user /home may not have been restored
+	echo
+	ECHO "If you chose to have your Original OS's /home use a separate partition during install, this will NOT be undone. /etc/fstab will still mount that partition as /home. If you want this undone, you can do so manually by modifying /etc/fstab."
+
+	#Done
+	echo "Uninstall Complete!"
+	exit 0
 }
 
 #Allows usage of "ECHO" instead of "echo"
