Moved code that creates squashfs to rlib. Changed all returns to exits
Moved squashfs code:
	The code will be required by rupdate too, and it was cluttering up rchroot
Changed all returns to exits:
	There was no point in doing "return 1" in functions, and later
	checking if the function came back with an error just to exit,
	especially since the function handles telling the user what
	happens

diff --git a/extras_14.10/rlib b/extras_14.10/rlib
--- a/extras_14.10/rlib
+++ b/extras_14.10/rlib
@@ -21,23 +21,23 @@ MOUNT_RS()
 	#anything is using it as a mount point
 	if [[ -d "$Orig_OS" ]]
 	then
-		#If something is mounted, return with an error
+		#If something is mounted, exit with an error
 		if mountpoint -q "$Orig_OS"
 		then
 			echo "Failed to mount RAM Session. Is it already mounted?"
-			return 1
+			exit 1
 		fi
 
 		#Try to remove the $Orig_OS
 		sudo rmdir "$Orig_OS" &>/dev/null
 
 		#If removing the $Orig_OS folder fails, like if it's
-		#not empty, return with an error
+		#not empty, exit with an error
 		if [[ "$?" != "0" ]]
 		then
 			echo "Failed to remove old $Orig_OS folder."
 			echo "Does it have files in it?"
-			return 1
+			exit 1
 		fi
 	fi
 
@@ -49,13 +49,13 @@ MOUNT_RS()
 	{
 		echo "Failed to mount $ROOT_UUID $Orig_OS"
 		UMOUNT_RS
-		return 1
+		exit 1
 	}
 
 	#If this function was passed the arg "root_only", exit here
 	if [[ "$1" == "root_only" ]]
 	then
-		return 0
+		exit 0
 	fi
 	
 	#Bind /proc
@@ -63,7 +63,7 @@ MOUNT_RS()
 	{
 		echo "Failed to bind /proc to ${Orig_OS%/}/${DEST%/}/proc"
 		UMOUNT_RS
-		return 1
+		exit 1
 	}
 
 	#Bind /dev
@@ -71,7 +71,7 @@ MOUNT_RS()
 	{
 		echo "Failed to bind /dev to ${Orig_OS%/}/${DEST%/}/dev"
 		UMOUNT_RS
-		return 1
+		exit 1
 	}
 
 	#Bind /dev/pts
@@ -79,7 +79,7 @@ MOUNT_RS()
 	{
 		echo "Failed to bind /dev/pts to ${Orig_OS%/}/${DEST%/}/dev/pts"
 		UMOUNT_RS
-		return 1
+		exit 1
 	}
 
 	#Bind /sys
@@ -87,7 +87,7 @@ MOUNT_RS()
 	{
 		echo "Failed to bind /sys to ${Orig_OS%/}/${DEST%/}/sys"
 		UMOUNT_RS
-		return 1
+		exit 1
 	}
 
 	#Bind /run
@@ -95,7 +95,7 @@ MOUNT_RS()
 	{
 		echo "Failed to bind /run to ${Orig_OS%/}/${DEST%/}/run"
 		UMOUNT_RS
-		return 1
+		exit 1
 	}
 
 	#Mount /boot, if it's not on the same partition as /
@@ -105,7 +105,7 @@ MOUNT_RS()
 		{
 			echo "Failed to mount $BOOT_UUID to ${Orig_OS%/}/${DEST%/}/boot"
 			UMOUNT_RS
-			return 1
+			exit 1
 		}
 	fi
 
@@ -116,7 +116,7 @@ MOUNT_RS()
 		{
 			echo "Failed to mount $EFI_UUID to ${Orig_OS%/}/${DEST%/}/boot/efi"
 			UMOUNT_RS
-			return 1
+			exit 1
 		}
 	fi
 	
@@ -127,7 +127,7 @@ MOUNT_RS()
 		{
 			echo "Failed to mount $HOME_UUID to ${Orig_OS%/}/${DEST%/}/home"
 			UMOUNT_RS
-			return 1
+			exit 1
 		}
 	fi
 
@@ -192,4 +192,38 @@ UMOUNT_RS()
 toLower() 
 {
 	echo $@ | tr "[:upper:]" "[:lower:]" 
+}
+
+#Create squashfs image
+CreateSquashfs()
+{
+	echo "Creating squashfs image"
+	echo
+
+	#Mount only the root filesystem of the Original OS
+	MOUNT_RS root_only
+
+	#Create squashfs image
+	#Note: We do NOT write the file directly to the one we boot
+	#from so that if the process gets interrupted and we reboot,
+	#we can still boot into the old image
+	sudo mksquashfs ${Orig_OS%/}/${DEST#/} ${Orig_OS%/}/live/filesystem.squashfs.new -noappend -always-use-fragments
+
+	#If there was an error, exit 1
+	if [[ "$?" != "0" ]]
+	then
+		echo
+		echo "Failed to create ${Orig_OS%/}/live/filesystem.squashfs"
+		UMOUNT_RS
+		exit 1
+	fi
+
+	#Move the newly created squashfs image to the location we boot from
+	sudo mv ${Orig_OS%/}/live/filesystem.squashfs.new ${Orig_OS%/}/live/filesystem.squashfs
+
+	#Inform user we are done
+	echo "mksquashfs created successfully"
+
+	#Unmount the root filesystem
+	UMOUNT_RS
 }
