Fixed mounting of /boot
When /boot is NOT on a separate partition from the Original OS's /,
we still need to mount it when we use rchroot or rupdate (rlib does
the mounting). This code makes that happen

diff --git a/extras_14.10/rlib b/extras_14.10/rlib
--- a/extras_14.10/rlib
+++ b/extras_14.10/rlib
@@ -119,6 +119,13 @@ MOUNT_RS()
 			UMOUNT_RS
 			exit 1
 		}
+	else
+		sudo mount -o bind "$Orig_OS/boot" "$Orig_OS/$DEST/boot" ||
+		{
+			echo "Failed to bind ${Orig_OS%/}/boot to ${Orig_OS%/}/${DEST%/}/boot"
+			UMOUNT_RS
+			exit 1
+		}
 	fi
 
 	#Mount /boot/efi, if we are running an efi system
