Added some error checking to rupdate

diff --git a/extras_14.10/rupdate b/extras_14.10/rupdate
--- a/extras_14.10/rupdate
+++ b/extras_14.10/rupdate
@@ -85,15 +85,44 @@ MOUNT_RS
 
 
 
+#################
+# Do the update #
+#################
 
-#Do the update
-sudo chroot $Orig_OS/$DEST/ /bin/bash -c "apt-get update; apt-get -y dist-upgrade; apt-get -y autoremove"
+#First, we resync the package index
+sudo chroot $Orig_OS/$DEST/ /bin/bash -c "apt-get update"
 
+#If there was a problem, exit
+if [[ "$?" != "0" ]]
+then
+	clear
+	echo "ERROR:"
+	echo "  There was a problem running \"apt-get update\". Scroll up to see what it was"
+	echo "  You may want to fix it using rchroot before running rupdate again"
 
+	#Unmount everything
+	UMOUNT_RS
 
+	exit 1
+fi
 
-clear
+#Now, we do the actual updates
+sudo chroot $Orig_OS/$DEST/ /bin/bash -c "apt-get -y dist-upgrade"
 
+#If there were problems, warn the user
+if [[ "$?" != "0" ]]
+then
+	clear
+	echo "WARNING:"
+	echo "  There was a problem with the update. Scroll up to see what it was"
+	echo "  You may want to fix it using rchroot before recreating the squashfs image"
+	echo
+else
+	#If there were no problems, remove any packages no longer required
+	#and clear the screen
+	sudo chroot $Orig_OS/$DEST/ /bin/bash -c "apt-get -y autoremove"
+	clear
+fi
 
 ##########################################################################
 # Check if /etc/kernel/postinst.d/zd_warn has set a flag that shows that #
